apiVersion: v1
kind: ServiceAccount
metadata:
  name: cs-team
  namespace: staging
 
---

apiVersion: v1
kind: Secret
metadata:
  name: cs-team-token
  namespace: staging
  annotations:
    kubernetes.io/service-account.name: cs-team
type: kubernetes.io/service-account-token

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cs-team-role
  namespace: staging
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - '*'
    resources:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cs-team-rolebinding
  namespace: staging
subjects:
  - kind: ServiceAccount
    name: cs-team
    namespace: staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cs-team-role


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-namespaces-role
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - namespaces
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: list-namespaces-cs-team
subjects:
  - kind: ServiceAccount
    name: cs-team
    namespace: staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: list-namespaces-role

  
 




 
