apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-team
  namespace: staging

---


apiVersion: v1
kind: Secret
metadata:
  name: product-team-token
  namespace: staging
  annotations:
    kubernetes.io/service-account.name: product-team
    type: kubernetes.io/service-account-token

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: product-team-role
  namespace: staging
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - '*'
    resources:
      - '*'
  - verbs:
      - get
      - list
      - watch
      - delete
    apiGroups:
      - '*'
    resources:
      - pods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: product-team-rolebinding
  namespace: staging
subjects:
  - kind: ServiceAccount
    name: product-team
    namespace: staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: product-team-role

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-namespaces-role
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - namespaces
      
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: list-namespaces-testuser
subjects:
  - kind: ServiceAccount
    name: product-team
    namespace: staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: list-namespaces-role
---

