apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: readeverything-deletepod
  rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - '*'
  - verbs:
      - delete
    apiGroups:
      - ''
    resources:
      - pods
